# ---------------------------------- Cluster -----------------------------------
# 集群相关的配置																|								
# ---------------------------------- Cluster -----------------------------------
cluster.name: elaticsearch
	* 集群的名称

# ------------------------------------ Node ------------------------------------
# 节点的设置																	|							
# ------------------------------------ Node ------------------------------------
node.name: node-1
	* 当前节点的名称

node.attr.rack: r1
	* 可以为当前的节点添加自定义的属性

# ----------------------------------- Paths ------------------------------------
# 存储目录的配置																|
# ----------------------------------- Paths ------------------------------------
path.data: D:\elasticsearch\data
path.logs: D:\elasticsearch\log
	* 数据存储目录和日志存储目录
	* 可以有多个目录, 使用逗号分隔

# ----------------------------------- Memory -----------------------------------
# 内存配置																		|
# ----------------------------------- Memory -----------------------------------
bootstrap.memory_lock: true

# ---------------------------------- Network -----------------------------------
# 网络配置																		|
# ---------------------------------- Network -----------------------------------
network.host: 192.168.0.1
http.port: 9200
	* 设置监听的网卡, 以及端口

# --------------------------------- Discovery ----------------------------------
#			
# --------------------------------- Discovery ----------------------------------
discovery.seed_hosts: ["host1", "host2"]
cluster.initial_master_nodes: ["node-1", "node-2"]

# ---------------------------------- Gateway -----------------------------------
# 
# ---------------------------------- Gateway -----------------------------------
gateway.recover_after_nodes: 3

# ---------------------------------- Various -----------------------------------
# 
# ---------------------------------- Various -----------------------------------
action.destructive_requires_name: true
